# Generated by Django 3.1.7 on 2021-03-02 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210302_2031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='author',
        ),
        migrations.AddField(
            model_name='images',
            name='blog',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.blog'),
        ),
    ]
