# Generated by Django 3.1.7 on 2021-03-03 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210302_2050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='author',
            new_name='Blogger',
        ),
    ]
