# Generated by Django 3.1.7 on 2021-03-03 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_blog_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogger',
            old_name='name',
            new_name='blogger',
        ),
    ]
