# Generated by Django 3.1.7 on 2021-03-03 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20210303_1015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='Blog',
            new_name='blog',
        ),
        migrations.AlterField(
            model_name='images',
            name='images',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.DeleteModel(
            name='Blogs',
        ),
    ]
