# Generated by Django 3.1.7 on 2021-03-03 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20210303_1530'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.blog')),
                ('blogger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.blogger')),
                ('images', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.images')),
            ],
        ),
    ]
