# Generated by Django 3.1.7 on 2021-03-03 17:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0016_auto_20210303_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='Blogger',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.blogger'),
        ),
        migrations.AddField(
            model_name='blogs',
            name='Bookmark',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='bookmark', to='api.blog'),
        ),
        migrations.AddField(
            model_name='blogs',
            name='added_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blogs',
            name='content',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.blog'),
        ),
        migrations.AddField(
            model_name='blogs',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='blogs',
            name='gist_embed',
            field=models.ForeignKey(default=None, max_length=200, on_delete=django.db.models.deletion.CASCADE, related_name='gist_e', to='api.blog'),
        ),
        migrations.AddField(
            model_name='blogs',
            name='image_embed',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='image_e', to='api.blog'),
        ),
        migrations.AddField(
            model_name='blogs',
            name='video_embed',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='video_e', to='api.blog'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blg', to='api.blog'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='images',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.images'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='usr', to=settings.AUTH_USER_MODEL),
        ),
    ]
