# Generated by Django 3.1.7 on 2021-03-03 18:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0019_auto_20210303_2334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='Blogger',
        ),
        migrations.RemoveField(
            model_name='blogs',
            name='Bookmark',
        ),
        migrations.RemoveField(
            model_name='blogs',
            name='added_by',
        ),
        migrations.RemoveField(
            model_name='blogs',
            name='content',
        ),
        migrations.RemoveField(
            model_name='blogs',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='blogs',
            name='gist_embed',
        ),
        migrations.RemoveField(
            model_name='blogs',
            name='image_embed',
        ),
        migrations.RemoveField(
            model_name='blogs',
            name='video_embed',
        ),
        migrations.AlterField(
            model_name='blogs',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.blog'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
