# Generated by Django 3.1.7 on 2021-03-04 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20210304_1412'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blogs',
        ),
    ]
