# Generated by Django 3.1.7 on 2021-03-04 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_remove_blog_blogger'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='Bookmark',
            new_name='bookmark',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='content',
            new_name='quote',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='added_by',
            new_name='user',
        ),
        migrations.DeleteModel(
            name='Images',
        ),
    ]
