# Generated by Django 3.1.7 on 2021-03-04 12:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0024_auto_20210304_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='bookmark',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='blog',
            name='gist_embed',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image_embed',
            field=models.ImageField(blank=True, default='', upload_to='emb_images'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='quote',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='blog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Blog', to=settings.AUTH_USER_MODEL),
        ),
    ]
